global using Microsoft.AspNetCore.Mvc;
global using Mooc.Application.Contracts;
global using Mooc.Application.Contracts.Admin;
global using Mooc.Application.Contracts.Admin.Dto;
global using Mooc.Application.Contracts.Dto;
global using Mooc.Core.ExceptionHandling;
global using Mooc.Core.Utils;
global using Mooc.Model.Option;
global using Mooc.Shared;
